background_opacity 1.0
output_name DELL U3415W
edge center-sized
lines 30
columns 140
hide_on_focus_loss yes
kitty_override allow_remote_control=socket-only
kitty_override listen_on=unix:/tmp/kitty-quick-access
kitty_override background #151515
