#!/usr/bin/env bash

# Claude Code pipes a JSON object to this script via stdin on each status line update.
input=$(cat)

# The human-readable name of the Claude model being used (e.g. "Claude Sonnet 4.6")
model=$(echo "$input" | jq -r '.model.display_name // "unknown"')

# Percentage of the model's context window that has been consumed so far in this session.
# Claude has a fixed context window (e.g. 200k tokens); as the conversation grows, this rises.
used_pct=$(echo "$input" | jq -r '.context_window.used_percentage // empty')

# Tokens sent TO Claude in the current API call (your messages + system prompt + tool results).
# A higher input token count means more of the context window is being used for history/content.
input_tokens=$(echo "$input" | jq -r '.context_window.current_usage.input_tokens // empty')

# Tokens generated BY Claude in the current API call (Claude's response).
# Output tokens are typically much smaller than input tokens.
output_tokens=$(echo "$input" | jq -r '.context_window.current_usage.output_tokens // empty')

# The maximum number of tokens Claude can hold in its context window.
# Typically 200,000 for standard models, or 1,000,000 for extended context models.
max_tokens=$(echo "$input" | jq -r '.context_window.context_window_size // empty')

# Current working directory from the JSON input.
cwd=$(echo "$input" | jq -r '.cwd // empty')

# Display path: relative to git repo root (including repo name) if inside a repo,
# otherwise relative to $HOME (shown with a leading ~).
display_cwd="$cwd"
if [[ -n "$cwd" ]]; then
  git_root=$(git -C "$cwd" rev-parse --show-toplevel 2>/dev/null)
  if [[ -n "$git_root" ]]; then
    repo_parent=$(dirname "$git_root")
    display_cwd=${cwd#"$repo_parent"/}
  elif [[ "$cwd" == "$HOME" ]]; then
    display_cwd="~"
  elif [[ "$cwd" == "$HOME"/* ]]; then
    display_cwd=~/${cwd#"$HOME"/}
  fi
fi

token_info=""
if [[ -n "$used_pct" ]]; then
  # Show context window usage as fraction/max (percentage) — when percentage hits 100%, Claude can no longer respond
  pct_rounded=$(printf '%.0f' "$used_pct")
  if [[ -n "$max_tokens" ]]; then
    # Derive total tokens used from percentage × max to match what used_percentage actually measures
    # (current_usage.input_tokens is only the most recent call, not the full conversation)
    used_tokens=$(printf '%.0f' "$(echo "scale=2; $used_pct * $max_tokens / 100" | bc)")
    used_k=$(printf '%.0f' "$(echo "scale=1; $used_tokens / 1000" | bc)")
    max_k=$(printf '%.0f' "$(echo "scale=1; $max_tokens / 1000" | bc)")
    token_info=" | ctx: ${used_k}k/${max_k}k (${pct_rounded}%)"
  else
    token_info=" | ctx: ${pct_rounded}%"
  fi
  if [[ -n "$input_tokens" && -n "$output_tokens" ]]; then
    # Show raw token counts for the most recent API call
    token_info="$token_info (in:${input_tokens} out:${output_tokens})"
  fi
fi

printf "\n \033[0;36m%s\033[0m\033[0;33m %s\033[0m\033[0;32m%s\033[0m" \
  "$model" "$display_cwd" "$token_info"
