#!/usr/bin/env bash

# 1. Search for text in files using Ripgrep
# 2. Interactively narrow down the list using fzf
# 3. Open the file in Vim
IFS=: read -ra selected < <(
  rg --color=always --no-heading --line-number --smart-case "${*:-}" |
    fzf --ansi \
        --exact \
        --delimiter : \
        --algo v1
)
[ -n "${selected[0]}" ] && nvim "${selected[0]}" "+${selected[1]}"
