views:
  v1/pods:
    sortColumn: AGE:asc
    columns:
      - NAME
      - PF
      - READY
      - STATUS
      - RESTARTS
      - CPU
      - MEM
      - '%CPU/R|R'
      - '%CPU/L|R'
      - '%MEM/R|R'
      - '%MEM/L|R'
      - IP
      - AGE
      - NODE
